AllCops:
  Exclude:
    - bin/*
    - config/initializers/simple_form.rb
    - db/schema.rb
  TargetRailsVersion: 6.0.3
Metrics/BlockLength:
  Max: 30
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
